name: listproject
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.10.0
  cupertino_icons: ^1.0.2
  date_time_picker: ^1.1.0
  equatable: ^1.2.2
  flutter_bloc: ^5.0.1
  flutter_bootstrap: ^1.0.2
  fluttertoast: ^7.1.1
  font_awesome_flutter: ^9.0.0
  http: ^0.12.2
  intl: ^0.16.1
  lottie: ^1.0.1
  rxdart: ^0.20.0
  shared_preferences: ^0.5.10
  hexcolor: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  fonts:
    - family : Poppins
      fonts :
        - asset: fonts/Poppins/Poppins-Regular.ttf
    - family : PoppinsMedium
      fonts :
        - asset: fonts/Poppins/Poppins-Medium.ttf
    - family : PoppinsBold
      fonts :
        - asset: fonts/Poppins/Poppins-Bold.ttf
    


  
  assets:
    - asset/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
